### ISSUE TITLE
Feature Request: Only warn about uncommitted change if aider will make change

### ISSUE THREAD

**Issue by jzhang-brex** [paul-gauthier/aider#106]
aider will warn me about `uncommitted changes` even when I type `/help`.
```
Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Create cache table if it doesn't exist in the cache database.
```

Another case is that I will ask a question w/o aider to make any change. In such scenario, it's not necessary to warm users about  uncommitted change

**Comment by paul-gauthier** [comment]
Yes, you are right. Aider currently skips the repo dirty check for `/exit` and `/commit`. I have added the other commands where it is safe to skip the dirty check.

I've merged that into the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

Unfortunately, there's no way to safely determine that you are "just asking a question" to GPT. We need to do the dirty check before sending GPT the question, because it may reply with a code change based on the current file contents.

**Comment by jzhang-brex** [comment]
I see. Have you considered postpone the point when aider ask to commit dirty change. For example, aider can determine whether it needs to make change after GPT replies; we can ask the user to commit dirty change at that point.

In addition, we can ask if the user want to stash the change or commit it. If the user want to commit it, what's the message will be.

**Comment by joshuavial** [comment]
I've wondered about `/set` and `/unset` commands in aider itself that would let us toggle core variables without restarting. Then perhaps we could do things like setting the dry-run flag to true as a hacky workaround for entering chat mode. 

Maybe it would be worth creating a dedicated flag for indicating whether we are in discussion mode or code editing mode, but I'm guessing you would probably want different system prompts and I'm not how often people would want to use aider for chatting vs editing.

**Comment by MohHeader** [comment]
> I'm not how often people would want to use aider for chatting vs editing.

I have a use case for this, but it could be unrelated to aider's goal.

I like to prepare something like a micro-steps development plan, as we consider aider as a the junior developer that we should explicitly tell it what to do exactly.

Then, we could still use GPT to act as a Senior Developer, and ask it not to code, but to prepare the plan for the Junior one.

For that to work, GPT needs at least two things:
1. Few documents from the PM (yes, GPT can act as that too)
2. Context and content from files related to the task at hand, which is where aider could be the perfect fit

TBH, I haven't used aider to prepare that type of plan yet, although I believe it could handle it. So it's more like a theory so far.

**Comment by paul-gauthier** [comment]
> Have you considered postpone the point when aider ask to commit dirty change. For example, aider can determine whether it needs to make change after GPT replies; we can ask the user to commit dirty change at that point.

Yes, I've been thinking about this quite a bit since you opened this issue, and I agree it would be desirable to minimize the number of times that we need to commit the dirty repo. 

But unfortunately, I don't think there's an easy way to make that better. 

Whenever you send a message to GPT, aider sends along the full content of all the files which have been added to the chat, as well as a bunch of data about the functions and variables in many other files in the repository. This other data is called the repository map. 

GPT is then free to reply with edits to any of the files that are in the chat session, but those edits may depend on data in the repository map. So it seems prudent to make sure that we have a clean repository before each message is sent to GPT. That way we can safely apply its edits to a known state and make it easy to undo back to that state if needed.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.
