### ISSUE TITLE
wrong path resolved

### ISSUE THREAD

**Issue by josh-i386g** [paul-gauthier/aider#1080]
### Issue

1. i run aider at /project/server/
2. aider detected my git root dir is /project/
3. i tried `/read /project/server/some-folder/some-file.ext`
4. it resolved to `/project/server/server/sole-folder/some-file.ext` which resulted to a file not found.

logs are here: https://gist.github.com/josh-i386g/edb43aa5091af851f29cd98f0a72a794

thank you

### Version and model info

latest

**Comment by Jannik-Hoffmann** [comment]
Alright, let's break this down:

The first problem you hit was when you were in the `server` directory. Aider was looking for the file at `/home/user/Documents/i386g/monolithic/server/server/src/functions/schemas.mts`. Aider was adding the current directory to the path you provided, which already included `server`.

The second issue came up when you tried to use `/read` with multiple files. The thing is, `/read` is AFAIK designed to work with one file at a time. When you give it multiple file paths, it treats the whole thing as one long filename, which obviously doesn't exist.

Now, about using `/add` instead of `/read` - `/add` actually supports multiple files while `/read` does not.

### Here's how you can get around these issues:

1. **For the first problem**: When you're in a subdirectory, try using absolute paths or move up to the root of your project before running Aider.

2. **For the second issue**: You'll need to use `/read` separately for each file you want to add as reference. It's a bit more typing, but it'll do what you want:

   ```
   /read server/src/functions/schemas.mts
   /read server/src/functions/tables.mts
   /read server/src/functions/policies.mts
   /read server/src/functions/items.mts
   ```

It's not the most elegant solution, but it'll get the job done until Aider maybe updates how it handles multiple files with `/read`!
```

**Comment by josh-i386g** [comment]
thank you!!!!
