### ISSUE TITLE
Uncaught OSError in pathlib.py line 331

### ISSUE THREAD

**Issue by lizliu27** [paul-gauthier/aider#1255]
Aider version: 0.54.8
Python version: 3.10.13
Platform: macOS-13.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 22.2.0 (64bit)
Git version: git version 2.39.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 552, in main
    coder = Coder.create(
  File "base_coder.py", line 156, in create
    res = coder(main_model, io, **kwargs)
  File "base_coder.py", line 355, in __init__
    fname.touch()
  File "pathlib.py", line 1168, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
OSError: [Errno 30] Read-only file system: '/chat-mode'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Looks like you tried to run aider on a read only filesystem. That won't really work, but aider shouldn't crash. I've fixed that.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
