### ISSUE TITLE
Can you make git diffs in the log optional?

### ISSUE THREAD

**Issue by funkytaco** [paul-gauthier/aider#127]
I'm using GPT-4 and it's pretty expensive so far. Please add an env variable to disable adding diffs to the logs. I'd prefer nothing besides an extremely brief git log or none at all preferably, maybe customizable to something like "WIP".

**Comment by joshuavial** [comment]
It's not exactly what you're looking for but you can get close to your desired behavior by running aider with the `--no-auto-commit` flag and then just run `/commit` and it will just use a short gpt3.5 generated commit message without the big diff.

The main thing to watch out for is if you run a bunch of edits without committing and the last one makes a mess of things you could lose any edits you have made since your last commit.

Re the costs, you might want to run the `/tokens` command periodically to make sure you are aware of how many tokens are being sent down and reset your chat history and drop files that aren't needed. I found my costs went down a lot when I started paying attention to the token count.

I also found it useful to use 3.5 for simple tasks like starting new files or writing a first draft of code and gpt4 for edits and enhancements - saves costs and can also save time (when it works), but runs the risk of having to do a bunch of rework if the task was too hard for 3.5

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

I'm not sure I understand the connection between "GPT-4 is pretty expensive" and "disable adding diffs to the logs". The git logs have no impact on the token costs of using GPT-4.

But perhaps I am misunderstanding your question?

@joshuavial has made some excellent suggestions for how to manage token costs!
