### ISSUE TITLE
Only 3 reflections allowed, stopping.

### ISSUE THREAD

**Issue by Yona544** [paul-gauthier/aider#1440]
### Issue

What does this mean and how can I change it 
Whenever this message shows up my code is messed up 

The error above this warning is **The LLM did not conform to the edit format.**
How about an option if The LLM did not conform to the edit format fall back to a other fallback modal to give it a try. 

### Version and model info

──────────────────────────────────────────────────────────────────Aider v0.55.0
Main model: claude-3-5-sonnet-20240620 with diff edit format,
infinite output
Weak model: claude-3-haiku-20240307
Git repo: \\192.168.0.35\YonaVmDataShare\Projects\KDSMenu\.git
with 51 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line
args

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by Shadetail** [comment]
Is it possible to increase the maximum number of reflections?

**Comment by honuonhval** [comment]
I had the same issue and dug in a bit, it doesn't look like there is a config we can change but you'd have to change the value in [base_coder.py](https://github.com/Aider-AI/aider/blob/bdafa842bdd6ce2922177c49deb7f1388495e6cc/aider/coders/base_coder.py#L75).  I think you can just say "continue what you were doing" or something like that to continue... that's what I went with.  Of course, you can also change the value too.

**Comment by fr34k8** [comment]
@honuonhval can you provide a patch ?

**Comment by honuonhval** [comment]
What do you mean?  Do you mean patch to configure max reflections in config?  Would it be something that you'd want @paul-gauthier ?

**Comment by brandonedley** [comment]
We want this

**Comment by Shadetail** [comment]
I thought about this a bit, about what the use case of this feature is. I see two:
 - User is afk (either intentionally or unexpectedly) and this feature prevents the model for failing for hours and hours emptying the user's wallet in terms of API credits.
 - History retains all the reflections, all the attempts of fixing the lit errors, filling up the available context and causing the model to effectively "forget" about everything that came before the 30 attempts to fix lint errors, even if attempt 30 was successful, having to re-explain the context of the task to the model seems like a bad outcome that this default of 3 reflections prevents.

If it's true that history management behaves like this (I think it does), then it does make sense to have a lower limit by default such as 3, but users should also be allowed to change this in some ini somewhere, and that ini should ideally mention these considerations.

And even better approach would be to improve history management such that once the lint error is fixed all the reflections are removed from history, making it seem from the model's perspective as if it got it right on the first try, making it so that from it's point of view, no lint errors ever happened.

That would leave only the first consideration to worry about. But for that use case, maximum of 3 seems unreasonable unless user is using o1 as the editor model, where each reflection could easily cost the user $1. While this could be adjusted to differ per-model, wouldn't a better solution be to not stop at 3 reflections, but simply pause and ask the user if he wants to continue trying? Maybe even allow the user to input the maximum number of reflections he'll allow.

**Comment by ghassentheben** [comment]
I’ve implemented a workaround to reduce the number of tokens consumed when trying to fix the lint errors if anyone is interested. It's basically a script that preprocesses and reduces the size of error messages before they’re passed to the reflection process. By trimming verbose outputs, this approach helps minimize context bloating.

This is an example of the script I use to build my .net project:
`
#!/bin/bash
OUTPUT=$(dotnet build 2>&1 | grep -E "error CS|error S" | sed -E 's#\[.*\]##' | sed -E 's#^.*/([^/]+\.cs)\(([0-9]+),([0-9]+)\): (error [A-Z0-9]+): (.*)#\1(\2,\3): \4: \5#' | sort | uniq)
if [ -n "$OUTPUT" ]; then
    echo "$OUTPUT"
    exit 1 # Exit with a non-zero code to indicate errors were found
else
    echo "No errors found."
    exit 0 # Exit with zero code for success
fi 

`
I use this as an executable script in my lint-cmd in the Aider configuration file.

**Comment by Sonkaryasshu** [comment]
> I thought about this a bit, about what the use case of this feature is. I see two:
> 
> * User is afk (either intentionally or unexpectedly) and this feature prevents the model for failing for hours and hours emptying the user's wallet in terms of API credits.
> * History retains all the reflections, all the attempts of fixing the lit errors, filling up the available context and causing the model to effectively "forget" about everything that came before the 30 attempts to fix lint errors or edit format issues, even if attempt 30 was successful, having to re-explain the context of the task to the model seems like a bad outcome that this default of 3 reflections prevents.
> 
> If it's true that history management behaves like this (I think it does), then it does make sense to have a lower limit by default such as 3, but users should also be allowed to change this in some ini somewhere, and that ini should ideally mention these considerations.
> 
> And even better approach would be to improve history management such that once the lint error or edit format error is fixed all the reflections are removed from history, making it seem from the model's perspective as if it got it right on the first try, making it so that from it's point of view, no lint errors or edit format errors ever happened.
> 
> That would leave only the first consideration to worry about. But for that use case, maximum of 3 seems unreasonable unless user is using o1 as the editor model, where each reflection could easily cost the user $1. While this could be adjusted to differ per-model, wouldn't a better solution be to not stop at 3 reflections, but simply pause and ask the user if he wants to continue trying? Maybe even allow the user to input the maximum number of reflections he'll allow.

I think we should really go for approach to pause and ask user OR allow config level control.

**Comment by j33433** [comment]
I mentioned the reflections error to claude 4.6 in aider. It understood and reworked its own edit. I was able to continue.
