### ISSUE TITLE
Uncaught PermissionError in pathlib.py line 1097

### ISSUE THREAD

**Issue by alaracalimaco** [paul-gauthier/aider#1666]
Aider version: 0.57.1
Python version: 3.10.15
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Python implementation: CPython
Virtual environment: Yes
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.39.5

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 367, in main
    loaded_dotenvs = load_dotenv_files(git_root, args.env_file)
  File "main.py", line 277, in load_dotenv_files
    if Path(fname).exists():
  File "pathlib.py", line 1290, in exists
    self.stat()
  File "pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/app/.env'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The permissions error and the path name suggest that you are running aider in a container environment. Please make sure all file permissions are setup correctly in this scenario (or please correct me if my assumption is wrong).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
