### ISSUE TITLE
Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by AbdullhHassan** [paul-gauthier/aider#1696]
Aider version: <module 'aider.__version__' from '/usr/local/lib/python3.12/site-packages/aider/__version__.py'>
Python version: 3.12.6
Platform: macOS-13.6.9-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 22.6.0 (64bit)
Git version: git version 2.15.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 428, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by fry69** [comment]
Thank you for filing this issue.

This error looks like it stems from installing aider via system packages (or `homebrew`), which do not respect the required dependencies aider needs, or the installation might otherwise be broken.

Please install aider separately from other Python modules, e.g. via `pipx` or `venv` or even Docker, see the installation instruction for options -> https://aider.chat/docs/install/install.html

This document may be also helpful -> https://aider.chat/docs/troubleshooting/imports.html
