### ISSUE TITLE
features to avoid a silly commit when you start aider on a file that doesn't exist

### ISSUE THREAD

**Issue by skybrian** [paul-gauthier/aider#184]
Using aider 0.11.0 in an initialized but empty repo, I ran:

```
aider hello.js
```

hello.js didn't exist, so it created it. Then it offered to commit it. I didn't know what the changes were, so I said yes.

This resulted in a commit with an empty hello.js file and a bogus commit message:

>  Refactor code to improve performance and readability.

Some possible improvements:

   * Don't offer to commit a file that's empty
   * Show the commit message and the files included in the change before asking the user if they want to commit.
   * Give the user the option of editing the commit message.

I guess if you want to do the commit yourself, you should press Control-C? It might be good to say that explicitly.

**Comment by joshuavial** [comment]
Thanks for taking the time to log an issue. Aider is designed to work with files only if they are in git to avoid data loss so option 1 probably wouldn't work.

A quick work around would be to just amend the message yourself with `git commit --amend` - you could also do the same with `/git commit --amend -m "new msg"` from aider itself though you'll need to include the `-m "msg"` flag until #185 is fixed.

I'm not sure how common it is that people would like to edit the commit msg from aider - if lots of people want it then it might be worth making a dedicated command, otherwise I wonder if the best approach is to update the docs with a tip on how to use the built in /git command to edit a commit msg.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue. I have also seen this, and it's on my shortlist of bugs to fix asap.

**Comment by paul-gauthier** [comment]
This fix just went out in v0.11.1. I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
