### ISSUE TITLE
litellm.APIConnectionError: APIConnectionError: OpenAIException - Service Unavailable

### ISSUE THREAD

**Issue by xoco70** [paul-gauthier/aider#1855]
### Issue

Aider v0.58.1
groq/llama3-70b-8192

I'm using Mac M1.
I'm trying to use aider with grok. I have a API KEY, and also exported it like stated in doc

auto-poster git:(master) ✗ aider --model groq/llama3-70b-8192

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.58.1
Main model: groq/llama3-70b-8192 with diff edit format
Weak model: groq/llama3-8b-8192
Git repo: .git with 128 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> can you please help me add some unit tests                                                                                                                                                                

```
litellm.APIConnectionError: APIConnectionError: OpenAIException - Service Unavailable
Retrying in 0.2 seconds...

```

It seems to be looking for OpenAI when I asked to use Grok

**Comment by fry69** [comment]
Thank you for filing this issue.

> It seems to be looking for OpenAI when I asked to use Grok

No, just because you read somewhere "OpenAI" does not mean you are talking to OpenAI's API.

Many LLM providers use the OpenAI API format as it is very popular, ans many clients use the OpenAI SDK to talk to those endpoints by changing the API base URL. The net result is that errors still contain "OpenAI" because it is the OpenAI SDK that is doing the work.

Otherwise follow these instructions -> https://aider.chat/docs/llms/groq.html

If you still get errors, it might be a problem with LiteLLM, your network or the groq API. Sadly LiteLLM is not very debug-friendly.

**Comment by fry69** [comment]
Looks like groq API had a hiccup. It is working now ->
```shell
$ aider --model groq/llama3-70b-8192 --no-pretty

Aider v0.58.1
Main model: groq/llama3-70b-8192 with diff edit format
Weak model: groq/llama3-8b-8192
Git repo: .git with 6 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args

> Hello.

Hello! I'm ready to assist you with making changes to the code. What changes would you like me to make?
Tokens: 2.2k sent, 24 received. Cost: $0.0013 message, $0.0013 session.
```
