### ISSUE TITLE
Uncaught FileNotFoundError in <frozen posixpath> line 415

### ISSUE THREAD

**Issue by kuatroka** [paul-gauthier/aider#1875]
Aider version: 0.58.1
Python version: 3.12.6
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 350, in main
    default_config_files = [conf_fname.resolve()]  # CWD
                            ^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1240, in resolve
    s = self._flavour.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 428, in realpath
  File "<frozen posixpath>", line 415, in abspath
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by kuatroka** [comment]
Thanks, I tried, but now I can't even replicate it. I'll be on a lookout if it happens again.
