### ISSUE TITLE
`auto-commits: false` has no apparent effect in YAML config

### ISSUE THREAD

**Issue by dgmulf** [paul-gauthier/aider#210]
While `no-auto-commits: true` has the intended effect in YAML configuration, and `--auto-commits` reverts this change, `auto-commits: false` has no apparent effect. Furthermore, I find it confusing that the two opposite flags create what appear to be duplicate but logically inverse YAML config settings.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue. I certainly agree that this isn't ideal.

I had aider fix this: https://github.com/paul-gauthier/aider/commit/0e9e037c06d4a355944be9a04877e120698e367c

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by dgmulf** [comment]
That solves the original issue. Thank you! Perhaps to avoid any confusion, aider could mandate using the affirmative form in the config file, like the AIDER_* environment variables? That would break backwards compatibility though, and it's a trivial detail.

**Comment by kke** [comment]
Btw maybe auto-commits: false should disable prompting for .gitignore modification

**Comment by paul-gauthier** [comment]
> Btw maybe auto-commits: false should disable prompting for .gitignore modification

Use `--no-git` if you don't want aider to do anything git related.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
