### ISSUE TITLE
Feature Request: Leverage MemGPT for very large code bases

### ISSUE THREAD

**Issue by ian-reay** [paul-gauthier/aider#289]
In very large code bases the tags can't fit in the context window. Being able to leverage MemGPT's memory structure might allow for effective use in very large code bases.

**Comment by ian-reay** [comment]
https://github.com/cpacker/MemGPT/tree/main/memgpt

**Comment by RaphaelFavero** [comment]
Would be great !

**Comment by paul-gauthier** [comment]
Thanks for trying aider and making this suggestion. 

Aider already works pretty well with large code bases, but I'm always looking to improve. 

It's possible that MemGPT could be a piece of that puzzle, but it doesn't look directly applicable. It seems more focused on handling a long conversation history, something aider already handles via summarization.

I'm going to associate this issue with issue #74, which discusses this general topic more broadly. I'll close this one as a dup, but feel free to re-open or file a new issue any time.

**Comment by ohadgk** [comment]
Hello,

Athusiastic aider user here, so first of all I want to say thanks for this incredible tool.

I'm posting on this closed issue because I think an integration between aider and something like memgpt can hold so much more potential other than just handling large codebases better.

If aider could have a long term memory, or the ability to "save" and "load" agents with the context of the pervious work, that can be a truly game changer.

Is there any thoughts in that direction?

**Comment by ian-reay** [comment]
I think the key topic here is how to effectively navigate code bases with millions of lines of code. AIs are pretty similar to humans. They can only hold so much personal knowledge of the code to aid them with navigating it. 

Much of the navigation of code is through experiences. If you are having a problem with X, you might also need to access Y and Z. This is memory. And this comes from real world experiences and history. 

In large code bases ( ie millions of LOC ) the only way I can see this working is to have a team of specialists. Each with their memories of the code. And each focusing on certain areas. Then have that Team try to solve the problem. 

In effect, autogen with aider as an example.
