### ISSUE TITLE
`<source>` tag in search/replace patches

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#317]
ChatGPT generates invalid patches sometimes. With "`<source>`" tag before filename. And Aider treats it as "`<source>filename`" file name. Those patches can be fixed with a special but simple parsing workaround. Can you update a parser for that case?

Aider Version: `v0.15.0`

```
<source>config.ini
<<<<<<< HEAD
... content removed ...
=======
... content removed ...
>>>>>>> updated
</source>
...

> Allow creation of new file <source>config.ini? n
```

**Comment by azazar** [comment]
And sometimes it generates patches like that (Aider v0.16.3):

```
<source>markdown
data_structures.md
<<<<<<< SEARCH
... content removed ...
=======
... content removed ...
>>>>>>> REPLACE
</source>
```

**Comment by azazar** [comment]
ChatGPT loves "<source>" tag for some strange reason.

**Comment by paul-gauthier** [comment]
Thanks for filing this issue. 

Aider actually encourages GPT to use `<source>` when the file being edited already contains the normal triple-backtick fence. 

But you have identified a corner case where aider isn't correctly noticing when GPT generates a malformed SEARCH/REPLACE block with `<source>filename.ext`. Aider normally notices such malformed S/R blocks and tells GPT to try again and fix the problem. I just made a fix so that aider correctly does this in the case you've identified.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
