### ISSUE TITLE
--map-tokens 0 when using unsupported language

### ISSUE THREAD

**Issue by NerdGGuy** [paul-gauthier/aider#321]
I recently realised tree-sitter was producing poor results for svelte and the resulting map tokens content was degrading performance and wasting tokens. I now run with --map-tokens 0. But it wasn't clear to me I should do this without running aider verbose and seeing the map context being sent.

- Provide a command to show current map (e.g. /map)
- Auto-detect (maybe based on file extensions or tree-sitter output?) if map-tokens should be disabled
- Maybe some details about how aider uses tree-sitter and how one might add in language better support for other languages (e.g. svelte)

In my specific case, svelte, I can see there is a svelte fork but am now sure how that could be incorporated in aider (https://github.com/Himujjal/tree-sitter-svelte).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I haven't encountered GPT becoming confused by a "basic" repomap before. What made you conclude that it was "degrading performance" ?

**Comment by NerdGGuy** [comment]
I should provide some context. The repo contains both .js and .svelte files. The .js files would produce tree-sitter output but those functions are not relevant to the svelte code I was working on.

Presently only anecdotal evidence. When using gpt-4 when a single file added reaches about 400lines (~3500 tokens) the failure rate for patches and coding errors would significantly increase. Removing the repo-map temporarily reduced the context provided and the model would perform better allowed me to refactor the code into separate files. The repo-map itself didn't appear to confuse the model, only increased the context window which I find would decrease the success rate for producing compilable/working code.

---

On a side note `gpt-4-1106-preview` is, in my opinion, performing much better on a 3902 tokens file even when I add over 500 tokens of other files. This matches with OpenAI's claim that the model performs better with larger contexts which even at the 5000 token context range I'm seeing.

**Comment by paul-gauthier** [comment]
It should be possible to add other tree-sitter languages to aider. But aider will need a bit of configurability to support this. It's definitely a good thing to consider.

Aider needs 2 things to support a language:

1. A tree-sitter language implementation for the language in question.
2. A `tags.scm` query file that provides s-expressions to identify the named code blocks in that language.

As you point out, there is a `[tree-sitter-svelte](https://github.com/Himujjal/tree-sitter-svelte)` language implementation. So that's good. But it has an empty `tags.scm` file: https://github.com/Himujjal/tree-sitter-svelte/blob/master/queries/tags.scm

So aider won't be able to find named code blocks to build a repo map.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by zakkor** [comment]
@paul-gauthier 
I would like to help out and add a `tags.scm` file for Svelte so that it can be an officially supported language.
Any tips/documentation on what `tags.scm` needs to contain? (I can create another issue for this specifically, let me know)

**Comment by zakkor** [comment]
Created an issue here: https://github.com/paul-gauthier/aider/issues/1194
