### ISSUE TITLE
Add mode that writes no files

### ISSUE THREAD

**Issue by skorokithakis** [paul-gauthier/aider#338]
I usually use aider as a one-off session, so I run it in my local directory, have it make a change, and then quit. I don't use any of the persistence, so it would be good if it could have an option to disable writing any temporary/aider-specific files, like with --no-git.

**Comment by paul-gauthier** [comment]
Thanks for jumping over here from HN. It's harder to follow conversations there without any notifications.

Thanks for explaining your use case. This seems like a reasonable request.

The only think I am struggling with a bit is aider's cache file. Aider processes all the source code in your repo with tree-sitter and other analysis in order to build the repository map. For larger repos, this scan takes some seconds (so aider shows a tqdm progress bar during the initial scan). It caches the results so aider can run quickly from then on.

If aider can't cache the results of that scan, it means every message you send will require a potentially slow re-scan of the repo.

**Comment by skorokithakis** [comment]
Thanks for making Aider! A good solution here might be to create the local cache in some temporary directory based on a hash of the directory path (eg /tmp/aider_a3d86f on Linux/Mac). This way, it's out of the way of my directory, but I still get the benefits until the next reboot.

As long as it's clearly communicated that this option will mean a (perhaps lengthy) rescan every so often, I think the user can make their own choice between not having the files or having the speed.

Then again, it might be perfectly reasonable to say I should just add the Aider files to my gitgnore and that's it :P In that case, though, it would be a bit tidier if all files could go into an `.aider` dir that I could ignore/delete with one line. IIRC, now it makes multiple directories/files in the root.

**Comment by paul-gauthier** [comment]
Aider should offer to add `.aider*` to your `.gitignore` when it launches?

And yes, I have considered moving everything under `.aider/` as the number of files has grown.

**Comment by skorokithakis** [comment]
I think it does offer already, but I use --no-git because I don't want git integration, so it's been a while since I saw that, which leaves me with some files I need to keep deleting every time. It's a bit of an edge case, but it's annoying to tell Aider "you don't need to touch git" but then get a bunch of files.

I'd much prefer to have the files go in a temporary directory, or be deleted when Aider exits, as my repos are small, but I can probably ignore the files as a second option. It's up to you and whether you think this is worth the trouble, really, as it's not a huge issue for me (having everything in one directory would definitely help my OCD though).

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to reopen it or open a new issue if you have more to discuss.
