### ISSUE TITLE
Aider, urllib3, python version

### ISSUE THREAD

**Issue by rope-hmg** [paul-gauthier/aider#365]
Every time I run aider I get the following:

```sh
/Users/me/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
```

The `warnings.warn(` is the end. After that I get the normal aider output:

```
Aider v0.18.0
Add .aider* to .gitignore (recommended)? y
Added .aider* to .gitignore
Model: gpt-4-1106-preview
Git repo: .git
Repo-map: using 2048 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

This is the first time I'm using it on my Mac. The relevant specs:

```
Chip: Apple M2 Max
OS:   13.3.1 (a) (22E772610a)
```

The error mentions this issue, but I'm not a python person and I don't really know what the best course of action is.
https://github.com/urllib3/urllib3/issues/3020

It looks like this is similar (or the same as) this issue: https://github.com/paul-gauthier/aider/issues/143

My current version of python is: `Python 3.9.6` and it was installed by default.

Thanks

**Comment by paul-gauthier** [comment]
Are you experiencing any problems? Or are you just concerned that you're seeing the warning? The issue that you link to says that the warning is fine and can be safely ignored.

**Comment by rope-hmg** [comment]
Just concern really. Also advice I guess. I'm not familiar with python or it's ecosystem so I'm not sure if I should worry or if it's something that will solve itself eventually.

**Comment by paul-gauthier** [comment]
It seems like you have an unusual install of the `ssl` module. This is probably something with your local python environment. But if it's a hassle to figure out and fix the issue, you can probably just ignore the warning.

**Comment by rope-hmg** [comment]
I'll take a look, but I probably won't get too into it. It's just a little distracting is all. I use aider at work on my Linux machine and it's been completely fine.

I'll close this issue since I guess there isn't anything for you to do.
Thanks for your time :)

**Comment by jhf** [comment]
I had the same issue, and came to this ticket.
The problem is that macOS system Python is not compatible with urllib3 as required by aider.
I had installed Python with homebrew, but in my case I my `~/.zshrc` file called `/usr/libexec/path_helper` that inserts the system bin directory ahead of the homebrew bin directory, so the recommended way of installing aider with `python -m pip install aider-chat` installs it with system python, and you get this error message.

I think the recommended installation for aider on macOS should change to recommend installing Homebrew from https://brew.sh and then run
```
brew install python
brew install pipx
pipx install aider-chat
```
That would be less surprising for macOS users doing the default install.
