### ISSUE TITLE
autocomplete files with `/add`

### ISSUE THREAD

**Issue by Morriz** [paul-gauthier/aider#390]
file detection would be nice ;)

awesome work!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by inigopascall** [comment]
I have the same question. I create new files (I'm working with Laravel, so this is usually done with a single command like `php artisan make:model`), and since these are the files I'm actively worked on, it means that a) I haven't added or committed these to git yet, while conversely b) these are precisely the files which I want to use Aider with.

This seems to present a little bit of a hiccup in the workflow logic, but perhaps I just need re-calibrate my thinking... 🤔
