### ISSUE TITLE
Achronological (and possibly redundant) elements in the prompt when making the first request

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [paul-gauthier/aider#397]
Consider the following scenario. I have a project with a single file `hello.py`, and I ask aider to make a change.
The language model invocations look like this:

```
system: backstory, examples, rules
user: here is the repo map, if you want to change something ask to make the files read-write, I'm not sharing any read-write files yet
assistant: ok
system: rules again
user: please do <what I ask>
(model completion) assistant: make hello.py read-write
```

```
system: backstory, examples, rules
user: here are the read-write files: hello.py content
assistant: ok
system: rules again
user: please do <what I ask>
assistant: make hello.py read-write
user: done
(model completion) assistant: <actual search-replace block>
```

Note that this is inconsistent, the file was already read-write in the story when the (simulated) assistant asked to make it read-write and the (simulated) user ageed.

Maybe this conversation could be skipped entirely. If not, maybe the content of the file should follow the read-write request:
```
...
assistant: make hello.py read-write
user: done
user: here are the read-write files: hello.py content
...
```

For comparison, when doing the second request, the ordering of messages is consistent:
```
system: backstory, examples, rules
user: please do <what I ask 1>
assistant: make hello.py read-write
user: done
assistant: <actual search-replace block 1>
user: updated
assistant: ok
user: here are the read-write files: hello.py content
assistant: ok
system: rules again
user: please do <what I ask 2>
(model completion) assistant: <actual search-replace block 2>
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Other than being a bit odd, is there a reason you are concerned about this small inconsistency? It's unintended result of a number of intentional decisions in how to construct a synthetic conversation history that is most effective for aider's pair programming style workflow. It should be harmless, but if you see evidence of a problem being caused please let me know.

**Comment by Vlad-Shcherbina** [comment]
No evidence of problems from this behavior, just noticed the oddity and wanted to bring it to your attention in case it matters.

Out of curiosity, why include the read-write requests in the conversation history at all? I get why past user requests and assistant's responses are useful to include (maybe the followup is related to them). However, "To do this, I need hello.py read-write. Done" seems to unlikely to contain any relevant details, and it takes (a small number of) tokens.

What do you think of the approach where in the final request, the assistant magically gets the right list of read-write files, but the story of how this list came about is not included?

**Comment by paul-gauthier** [comment]
Because the r/w requests can occur organically mixed in with longer text from both the user or GPT. GPT might mention a file it needs along with a longer explanation about the plan for changing the code, etc. There's no easy way to just omit the r/w request from the conversation history.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
