### ISSUE TITLE
Running RepoMap in isolation

### ISSUE THREAD

**Issue by je-miller** [paul-gauthier/aider#45]
Given the following test, shouldn’t I see output similar to the sample tree found in the ctags.md?  Currently I’m only seeing filenames in the output.

```python
    def test_my_repo_map(self):
        temp_dir = os.path.abspath("../aider")
        rm = RepoMap(root=temp_dir)
        chat_fnames = [temp_dir+'\\main.py', temp_dir+'\\io.py']
        other_fnames = []
        ranked_tags_map = rm.get_ranked_tags_map(chat_fnames, other_fnames)
        print("\n" + ranked_tags_map)
        self.assertIn("append_chat_history (self, text, linebreak=False, blockquote=False)", ranked_tags_map)
```

============================== 1 failed in 0.87s ==============================
FAILED                    [100%]
io.py
main.py

OS: Windows 11

ctags --version
Universal Ctags 6.0.0(v6.0.0), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 16 2022, 02:15:28
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +win32, +wildcards, +regex, +gnulib_regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2

**Comment by paul-gauthier** [comment]
When you launch aider from the command line, does it report `Repo-map: universal-ctags using 1024 tokens` ? That will let you know for sure that aider is able to find and use your universal ctags installation.

Also, aider tries to "distill" down the full ctags data in order to fit the repo-map into a specified token budget (1024 tokens by default). Otherwise large repos would have maps that would just exhaust the context window. This is functionality from the Future Work section of the repo map article, but it's live in the tool now. I just haven't had a chance to write it up.

If you do `RepoMap(map_tokens = 1024*1024)` to tell it to use an extremely large number of tokens, it should include everything that ctags outputs.

https://github.com/paul-gauthier/aider/blob/166ecdcbd0b86847088dc195ede37f7b77227859/aider/repomap.py#L72

**Comment by je-miller** [comment]
"This is functionality from the Future Work section of the repo map article, but it's live in the tool now. I just haven't had a chance to write it up."
Thanks! This gave me the clue I needed. I wasn’t aware distillation was active, but in my case I want to experiment on repomap without it...  Then possibly explore writing my own distillation routine.
For now, I just threw in a flag and added the following code in get_ranked_tags

```python
        if self.skip_distillation:
            result = []
            for (fname, ident) in definitions:
                result += list(definitions.get((fname, ident), []))
            return result
```
