### ISSUE TITLE
Output to Chat Not working in .22 and .23

### ISSUE THREAD

**Issue by transcendr** [paul-gauthier/aider#467]
It seems both version 0.22.0 and 0.23.0 no longer handle adding output from commands to the chat properly. I had to roll back to 0.21.0 to get this extremely useful functionality back.

not working
![image](https://github.com/paul-gauthier/aider/assets/37011672/97d64329-70b6-4b94-a8f4-04f415d2c6be)

0.21.0 - working
![image](https://github.com/paul-gauthier/aider/assets/37011672/808b3af4-3ef7-4a25-b19e-42e8bb8e3056)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like it was a bug in the `!` shortcut for `/run`. The actual `/run` command seems to work fine in all versions.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. Or you can always just use `/run` in the meantime.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
