### ISSUE TITLE
FR: add docstrings, types and tests to udiff_coder.py

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [paul-gauthier/aider#493]
Hi,

I'm building a piece of code that needs to merges some texts iteratively using LLMs and when the text gets too long it can get quite expensive (and even at time outright fail)  to  have the LLM produce the whole output.

I figured I'd ask the LLM to produce unified diff formatted answers but so far it's been unrealiable, even with GPT4.

This lead me to `aider` which seems to have the best implementation of diff handling for LLMs I've ever seen **(congrats!).**

My app is not cli though, it's a python script so basically I think I'd like to add aider as a dependency to my project and only use the content of `udiff_coder.py`.

Looking at the code I'm running into some issues and decided to come ask directly for some clarifications. And being probably not the only one I figured I might as well formulate a request.

Would you be so kind as to do **any** of the following regarding udiff_coder.py : 
* add at least a minimal docstring to each function (especially to indicate the expected arguments values)
* add typing indicator to the inputs and outputs of each function
* add to `tests/test_udiff.py` more tests, especially tests for things more advanced than only `find_diffs` as that would have the dual benefits of 1 making the code more robust and 2 being examples of how the diffs can be used in code

Is that something you can consider doing? Thank you very much.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You're welcome to make use of the udiff code from aider, according to the Apache 2.0 license requirements. But be aware that it is not currently intended to be supported as an stable, externally used and supported library/module. It is very much under active development and revision, so I am reluctant to pretend otherwise.

Of course, docstrings, types and tests are all generally useful and good and they will naturally improve with time as I revisit parts of that code.

**Comment by thiswillbeyourgithub** [comment]
Alright, thank you very much. I'll close this for now.

I'll either fork (and credit of course) the relevant parts of the code or try to use aider directly (maybe).

Have a nice day
