### ISSUE TITLE
[BUG] aider can cause data loss

### ISSUE THREAD

**Issue by NightMachinery** [paul-gauthier/aider#513]
```
Aider v0.26.1
Model: gpt-4-1106-preview using udiff edit format
Git repo: ../../.git with 287 files
Repo-map: using 1024 tokens
Added autoload/forked/HighLight.el to the chat.
```

I asked `aider` to do a change, and it did. The change was wrong, so I used `/undo`. Then I noticed I had lost some uncommitted changes in my git repo.

There was no warning.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider takes great care to commit any pending edits to the before making any changes itself. See the FAQ for more details:
https://aider.chat/docs/faq.html#how-does-aider-use-git

Can you be more clear and specific about exactly what you think happened?

**Comment by NightMachinery** [comment]
> Aider takes special care if GPT tries to edit files that already have uncommitted changes (dirty files). Aider will first commit any preexisting changes with a descriptive commit message. This keeps your edits separate from GPT’s edits, and makes sure you never lose your work if GPT makes an inappropriate change.

Looking at my git history, I have no commits by aider. The files where I had data loss where not being edited by GPT's diffs. My guess is that aider is trying to do too much magic, and there are some subtle bugs. 

I suggest adding a `--strict` mode where aider will refuse to do anything when the repo is dirty at all.

**Comment by NightMachinery** [comment]
Here are the log files where the data loss happened:
[.aider.chat.history.md](https://github.com/paul-gauthier/aider/files/14704501/default.aider.chat.history.md)

**Comment by paul-gauthier** [comment]
Aider is very very careful about ensuring it never causes loss of your manual work. It's been a core principal since the project started.

The log you sent show that aider applied edits to `autoload/forked/HighLight.el` and then you did `/undo` to remove them.

```
> Applied edit to autoload/forked/HighLight.el
> Commit 1419fc1 aider: Refactored `hlt-highlight-regexp-region` to return a list of overlays created for highlighting.
...
#### /undo
...
The above commit 1419fc1 was reset and removed from git.
```

It does not appear to have touched any other files in the repo. Aider always prints "Applied edit to xxxx" if it edits a file. Grepping the log you sent only shows that one edit was made.

**Comment by NightMachinery** [comment]
@paul-gauthier Well, I have had data loss across several other files in this project. And this is the first time ever I have had such a data loss. So I am sure this is aider's fault. I can send further logs if they are stored somewhere.

**Comment by paul-gauthier** [comment]
Thank you for providing more information and detail. I was able to track this down, confirm it was a bug, add test coverage and fix the issue. It was possible for `/undo` to remove dirty changes from files which were not part of the commit being undone.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by NightMachinery** [comment]
@paul-gauthier Thanks. I have updated.

I still prefer having the `--strict` option, as I usually have a lot of uncommitted changes. I use `git add -p` every month or so to create multiple commits in one go. So I am very adverse to data loss, and I prefer `aider` just refusing to work on a dirty codebase.

**Comment by paul-gauthier** [comment]
Your use case is fairly unusual, but you could just run aider via a shell script if you want it to refuse to run on a dirty repo:

```bash
if git diff-index --quiet HEAD --; then
    # The repository is clean
    aider $* 
else
    echo "Repository is dirty"
    exit 1
fi
```
