### ISSUE TITLE
[improvement] Support Language Server in addition to ctags

### ISSUE THREAD

**Issue by OleksandrKucherenko** [paul-gauthier/aider#527]
References:
- https://langserver.org/
- https://github.com/typescript-language-server/typescript-language-server

Thanks!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider no longer relies on ctags. It now uses tree-sitter to analyze the code base.

https://aider.chat/2023/10/22/repomap.html

Is there a particular reason why you think it would be good to add LSP support? It is quite cumbersome for users to have to find, install, run an LSP server for every language they wish to work with. Tree-sitter is nice because it supports most popular code languages out of the box.

**Comment by OleksandrKucherenko** [comment]
LSP become a de-facto standard in webeditors, it has wide range of supported languages and great support from big brands like Microsoft, google, etc. It can be a big step in integrating aider into corporate/enterprise dev environments.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
