### ISSUE TITLE
Feature: respect indent in brace-based languages

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#566]
Claude 3 Opus likes to append methods to a Java/Kotlin class by doing a search/replace on an empty block whilst providing indented text. Aider just adds this to the end of the file, but it would be smarter to spot when the file ends with a brace and position the newly inserted block within the right scope, as determined by computing the minimum indent of the provided block.

Example:

```
 <<<<<<< SEARCH
 =======
     private fun invokeTask(task: BuildTask, cacheKey: String?, retryCount: Int = 0): Any? {
         check(retryCount <= maxRetries)
         return try {
             executeTask(task, listOf(task), 0, cacheKey)
         } catch (e: RetryLater) {
             if (retryCount < maxRetries) {
                 Logger.info("Task ${task.taskDisplayName} requested retry (attempt ${retryCount + 1}): ${e.message}")
                 if (e.delay != null) {
                     Logger.info("Waiting ${e.delay} before retrying ${task.taskDisplayName}")
                     Thread.sleep(e.delay.toMillis())
                 }
                 invokeTask(task, cacheKey, retryCount + 1)
             } else {
                 Logger.warn("Task ${task.taskDisplayName} failed after $maxRetries retries")
                 throw e
             }
         }
     }

 >>>>>>> REPLACE
```

Here, the right place to add the new method is inside the class, so one line above where aider chooses to put it.

**Comment by paul-gauthier** [comment]
I think this is probably best treated as a generic "edit error". It would be hard for aider to enforce per-language grammar rules in edits. Sometimes the LLM will make edit errors unfortunately. Aider tries very hard to prevent this, but it can still happen.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Qubhis** [comment]
Something similar happens to me as well, when using `diff` mode. I'm using gpt-4o. GPT correctly reasons where to make change, it was at the end of if branch in my example situation, but produces SEARCH block with indentation and closing curly brace. '       }'. This results in replacing wrong place in the file since there are 8 of such places in the file.

I spent half a day to try go around it mainly by modifying aider's system prompt in `editblock_prompts.py`, but it returned that in 9 out of 10 tries. 

```typescript
<<<<<<< SEARCH
                         }
=======
                             equationsToCalculate.push("factorial");
                         }
>>>>>>> REPLACE
```

So, I just reverted any changes made by aider (I don't use auto-commit feature) and followed with prompt `the diff is not sufficient for <concerned_filename>`, and it returned the correct SEARCH/REPLACE block.

```typescript
<<<<<<< SEARCH
                             equationsToCalculate.push("exponent");
                         }
=======
                             equationsToCalculate.push("exponent");
                             equationsToCalculate.push("factorial");
                         }
>>>>>>> REPLACE
```
