### ISSUE TITLE
How to configure LiteLLM for use of other LLMs

### ISSUE THREAD

**Issue by daniel-butler-irl** [paul-gauthier/aider#642]
### Issue

I have read the doc for other LLMs here https://aider.chat/docs/llms.html#other-llms
However it is not clear to me how to use the other LLMs that LiteLLM supports.
Example I have tried with IBM WatsonX:
https://docs.litellm.ai/docs/providers/watsonx
I configured an env file with:
```env
WATSONX_URL=https://us-south.ml.cloud.ibm.com
WATSONX_APIKEY=XXXXXXXXXXXXXXX
WATSONX_TOKEN=XXXXXXXXXXXXXXX
WATSONX_PROJECT_ID=XXXXXXXXXXXXXXX
```
and executed with 
`aider --env-file watsonx.env --models watson`
`aider --env-file watsonx.env --models ibm`

I see none of the WatsonX models, I expected to see something like `watsonx/ibm-mistralai/mixtral-8x7b-instruct-v01-q`.I am unsure where to go from here to connect to the instance.

Any help here would be appreciated thanks.

### Version and model info

Aider 0.36.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

It can't list the model because it's not present in the litellm database of models. Aider should be able to access the model you want to use if you use `--model watsonx/ibm/granite-13b-chat-v2` or whatever. Aider will print a warning that you're asking it to connect to a model that it doesn't know about. But that's ok.

https://aider.chat/docs/llms.html#model-warnings

**Comment by daniel-butler-irl** [comment]
Great thanks. That was my bad I should have gone to the link in the output. 
![image](https://github.com/paul-gauthier/aider/assets/10742925/0d1874bd-a27c-4882-87ee-1ec6ba130ac4)

This explanation makes sense. However, could the output be a warning (yellow)?  I saw red and thought error it must be broken...

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
