### ISSUE TITLE
Feature Request: Learn from Documentation

### ISSUE THREAD

**Issue by jasoncmcg** [paul-gauthier/aider#69]
Feature Request: Learn from Documentation
Example implementation:

Use ChromaDB (or something along those lines) to create and store researched documentation on a newer library (or one that is unknown to GPT), like langchain or EbitenUI. 

The user could say 
_/research langchain_
Or maybe 
_/research https://pkg.go.dev/github.com/ebitenui/ebitenui_

**Comment by yozef** [comment]
Exactly the use case I'm looking for. The LLM (OpenAI GPT-4) is not aware of some newer libraries, and their usage.

**Comment by rjohnson318** [comment]
Something like this would be nice to get that documentation into a place where aider can access it. https://github.com/StanGirard/quivr

**Comment by jasoncmcg** [comment]
> Something like this would be nice to get that documentation into a place where aider can access it. https://github.com/StanGirard/quivr

I liked that until I saw it require a Supabase account. ChromaDb can be run locally on business-class machines.

**Comment by rjohnson318** [comment]
true, maybe we can replace Supabase with ChromaDb...?

**Comment by fahmad91** [comment]
Are there any plans to implement this anytime soon? This feature will be extremely handy especially as I've found aider seems to implement outdated or deprecated code when working with new libraries that aren't part of the base model. Telling it to pull from the latest developer docs will drastically increase its accuracy.

**Comment by ryanfreckleton** [comment]
Probably https://github.com/kagisearch/vectordb would be a better fit than Chroma or the other systems.

I've had some success with other experiments running HTML documentation through html2markdown and then summarizing it into a cheat sheet, but the primary issues here will be figuring out a reasonable RAG approach for Aider and extracting relevant docs.

**Comment by joshuavial** [comment]
https://github.com/fleet-ai/context might give us an easy library to build on top of

**Comment by joshuavial** [comment]
Have done a bit more of a deep dive into fleet context and am thinking about the following approach

- use @ prefix in query (like cursor) to tell aider which libraries we want to get context from (e.g. @langchain @openai @pandas etc.)
- use the [fleet langchain integration](https://python.langchain.com/docs/integrations/retrievers/fleet_context) to get the documents that are relevant to that query 
- add them as context to the query

@paul-gauthier how would you feel about adding a langchain dependency to the project?

We could also have it so that the document retrieval is a separate query `@langchain how to use fleet-context to retrieve embeddings` with the outcome being only some documents added to our context window. Or it could be 'achieve goal xyz @pandas @langchain' where the document retrieval is done in the same step as directing Aider. Keen to hear people's thoughts on which approach they would prefer?

In terms of options I think we could
a) give the user a lot of visibility / control over the context retrieved (think parallel to how files are currently tracked). /list-contexts /clear-contexts /rm-context 3 etc.
b) give them less control - contexts are more or less invisible in the ui
c) maybe b) by default with an option to jump into a) for people who like complexity & control?

Given the overall strategy of wanting people to think less about the context and just have aider figure it out maybe we can think about the context management commands more as internal functions that aider will start to call as it gets more capable and keep the ui focused on what the user wants to achieve?

In terms of integrating with fleet, I notice the author mentioning the intention to add rust and js in the future as well as moving beyond the openai embedding model to some open ones. I think the main call we'd need to make is do we leverage the fleet api for querying contexts or try and query them locally

**Comment by arabold** [comment]
I'm very new to aider (and relative new to LLMs in general), so I might overlook something obvious here, but I think things could be as simple as allowing aider to fetch a specific website and add it to the context as documentation. Sure, indexing the docs for whole libraries would be awesome, but a first step could be to just point it to the right location manually, i.e. "Implement a Next.js modal using a parallel route as described in https://nextjs.org/docs/app/building-your-application/routing/parallel-routes". 

Fetching the page and adding it to the context (MemoryVectorStore) would solve this quite elegantly without adding much complexity, wouldn't it?

**Comment by joshuavial** [comment]
@arabold yes, I think that could work for a whole bunch of use cases.

I like the approach of just detecting a url in the input string - I think most of the work will be in making it resilient to a whole bunch of different websites, so it might be a game of maintenance whack a mole.

I wonder about whether the additional context is loaded for that single query or if it's added to the conversation. If it's added to the conversation I'm curious about the UI component - do we have a section called 'additional context' with it's own add / remove sort of features?

**Comment by paul-gauthier** [comment]
Given that aider has the `/web` command to download URLs and add them to the chat, I'm going to close this issue for now. But feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Astlaan** [comment]
Cursor allows one to add documentation from the web to project. Can Aider do this?

With Cursor you can provide it with the entry point URL to some web documentation. It explores the whole documentation website and "Indexes" it's contents (I guess it stores them in a vector database).

**Comment by lkoelman** [comment]
After working with the `/web` command, I really feel it isn’t a suitable alternative to scraping documentation pages  from a landing page/index or providing something like tool use and RAG to find docs automatically. Manually finding specific docs pages is definitely a time killer (I feel like a spoilt brat while typing this).

Would it be possible to add it using something like https://docs.crewai.com/tools/codedocssearchtool ?

**Comment by codyseally** [comment]
> After working with the `/web` command, I really feel it isn’t a suitable alternative to scraping documentation pages from a landing page/index or providing something like tool use and RAG to find docs automatically. Manually finding specific docs pages is definitely a time killer (I feel like a spoilt brat while typing this).
> 
> Would it be possible to add it using something like https://docs.crewai.com/tools/codedocssearchtool ?

Totally agree with this. The `/web` command never worked properly for me when giving it any form of documentation. This is not the feature request of this issue. What is needed is a form of RAG, possibly using the crew.ai link pasted above. Without giving the agent access to the most recent version of the documentation of whatever libraries you are using, the local LLM is extremely limited and unusable for any serious work.

**Comment by Sigfrodr** [comment]
+1. Llm is not great at all with recent/not so popular libs/frameworks. Even cloud models.

**Comment by TheSnowGuru** [comment]
It would be better to use mcp instead of reading api docs for integrations.



Shay Ronen
Offpista Media Group
