### ISSUE TITLE
Feature Request: Automatic File & Context Window Access Management

### ISSUE THREAD

**Issue by TimDommett** [paul-gauthier/aider#74]
The quality of output and autonomy of Aider is excellent, however, the main limitation of autonomy is the requirement for the user to manage Aiders access to files and to ensure the context window size is not overwhelmed. If the management of file access and managing of the context window was offloaded to the AI to manage, it shouldn't need much, if any, input from the user to complete tasks.

I'm not sure if this is possible, but it could potentially achieve this if it was able to:
1. Autonomously check and manage the current amount of used tokens and take actions based on this check.
2. Analyse if any files can be dropped safely. 
3. Have an option to add files without a user accepting the request.
4. Trim non-relevant chat history.
5. Chunk large files so it can access a single function in a large file instead of the entire file.
Hopefully, with these capabilities, it could complete even longer tasks without any input from the user.

This is the first autonomous agent system that we've successfully been able to incorporate into our team's workflows so thanks very much to the creators and contributors!

**Comment by berkeleymalagon** [comment]
I'm very new to the project (a few hours), so first of all, thank you for this great work!

+1 on this request - this is the main point of friction. I was under the impression the ctags integration was specifically for giving Aider the context of which files it should work with? disclaimer, I haven't looked at the code at all and dont understand the specific tradeoffs at play

i asked aider to give me a list of files it thinks would be relevant and it took a gpt-style generic guess referring to files that dont exist in my repo. I was hoping it'd write me a command i could just copy and paste to give it access to files it needs

Amazing work here

**Comment by paul-gauthier** [comment]
Yes, the goal is to eventually have aider/GPT manage all of the file access automatically! But we aren't there yet. This is ongoing work. You can see some discussion about next steps in the [future work](https://aider.chat/docs/ctags.html#future-work) section of the repo-map documentation.

In many cases, the current ctags repo-map enables the kind of request you're describing. GPT can figure out which files it will need to edit and ask permission to open them. But the current repo-map is not always enough, depending on the complexity of the repo, etc.

The repo-map has another important function. Even if GPT is only editing code inside one file, it needs to understand the overall structure of the codebase and be aware of other subsystems, modules, etc. The code it is writing may need to call other modules, etc. The repo-map provides this context as well. So even if you only add 1-2 files to the chat, GPT will have the big picture in hand when it edits them.

Also, just to be sure your aider is using ctags, can you see the following lines of output when you start aider?

```
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
```

**Comment by paul-gauthier** [comment]
You've got access to 32k!

With that much context window, you could try using a larger repo map.  The default is 1024 tokens, but you could try larger with something like `--map-tokens 4096`. 

You can also use `--verbose` to see the map it is sending (plus a ton of other debug info).

**Comment by berkeleymalagon** [comment]
Ooooh, that’s good to know! I will try that asap and see how the behavior changes.

Thanks for the tip!

How can I best get involved and help the project?

**Comment by younes-io** [comment]
+1 to this `awesome` feature request  & +100 to `Aider` !
Please let me know if you need any help to move forward with this.

**Comment by achristianson** [comment]
There's two other major things we can do to alleviate the context pressure:

## Solution 1: Summarization

If our context grows beyond the limit, we can apply summarization techniques to reduce the input so that it fits in the context window. This can even be done with a custom prompt so that the summarization is done with the semantics of the original request in mind. For example, we can prompt: "reduce this text by 75%. do so by first eliminating any content that is not relevant to <user's aider query>".

This summarization prompt is applied by mapping the prompt onto a set of chunks, or a rolling window, or a divide & conquer algorithm.

## Solution 2: Embeddings Search in Vector DB

In this solution, we take the entire codebase, divide the entire thing up into chunks, generate embeddings, then store those in a vector db (chroma db). We can then generate embeddings on the user's query at runtime and search the vector db for vectors closest in proximity to the input, which will be semantically similar to the input. This vector search can give us just the small chunks of relevant info that we can put in the context window.

**Comment by joshuavial** [comment]
FYI - summarization was added in [v0.11.0](https://github.com/paul-gauthier/aider/releases/tag/v0.11.0)

I'd be curious about how well a vector search would perform and think it's worth investigating. I think it would be good if any vector stuff was lined up with the idea of providing extra context from documentation or other codebases similar to the suggestion in #69

**Comment by fahmad91** [comment]
I recently came across an AI-powered code editor called [Cursor](https://www.cursor.so/). Although one could argue that it's not as powerful as Aider, I found its approach to handling documentation quite interesting and thought I would share it here. Hopefully, this will get people thinking about how it could potentially be integrated into Aider.

Basically, Cursor has the ability to learn from documentation by scraping the docs site and saving it as an embedding. Then, you can simply use @docs_library_name to include the embedding as part of your prompt. I believe a feature like this could be extremely useful if we can figure out how to implement it into Aider.

**Comment by olafgeibig** [comment]
@fahmad91 this is a feature that I would also like have with aider. Recently I tried to code a plugin for a DAW with the help of aider but I failed terribly because GPT-4 had no knowledge of the rather exotic API. With the RAG feature fahmad91 proposes it would be possible ingest the documentation and the code examples for that API and then add vector search embeddings to aider's context.

**Comment by man0l** [comment]
Did somebody tried to use embedding or even MemGPT?

**Comment by younes-io** [comment]
> I recently came across an AI-powered code editor called [Cursor](https://www.cursor.so/). Although one could argue that it's not as powerful as Aider, I found its approach to handling documentation quite interesting and thought I would share it here. Hopefully, this will get people thinking about how it could potentially be integrated into Aider.
> 
> Basically, Cursor has the ability to learn from documentation by scraping the docs site and saving it as an embedding. Then, you can simply use @docs_library_name to include the embedding as part of your prompt. I believe a feature like this could be extremely useful if we can figure out how to implement it into Aider.

I use Cursor but its indexing / embedding doesn't offer good results. I don't know what they use behind the scenes, to embed and to search embedded vectors, but it's not impressive for now..

**Comment by paul-gauthier** [comment]
Aider now does a nice job of suggesting which files to edit if you chat without any already added. 

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by VanceVagell** [comment]
In a project with very large (perhaps legacy) code files, I'm finding that even /add'ing one very large file in Aider can add to time/costs significantly. I'm using local models, so I'm more concerned about time, but cost in terms of tokens is correlated.

I would much prefer if Aider could allow the LLM to read _subsets_ of a file, rather than the entirety of the file, especially during the planning phase (e.g. /ask or architect mode). If the LLM determines a file needs to be completely added to apply the fix or feature successfully so be it, but right now even planning uses a massive amount of tokens because the entirety of every file of potential interest is added to the context.

The only partial workaround I'm aware of, is for me to manually manage the context with /read and /add, which means I pretty much need to pre-architect the solution, and even then there's no way for me to tell it to only look at subsets of those files that are actually relevant.

By comparison, a human software engineer would only read the most likely portions of the potentially relevant files before applying a fix or building a feature, they would not read all potentially relevant files from top to bottom.

The result of this is that for use with a local model, the inefficient use of context with regard to relevant code snippets makes it not very useful except for very narrow uses where I want it to do something trivial to a small file.

To be clear, the local models I'm using have large context (100k-200k), such as GLM 5.2 Q5. I'm not talking about small or more limited models. But they slow down significantly with unnecessary context usage.
