### ISSUE TITLE
Feature request: /undo and /diff should do something useful if last commit was not detected to be by aider.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#76]
Currently /undo and /diff is not accepted if aider doesn't know whether last commit is done by itself or not.

A more useful result is either:

- aider suggests using /run
- aider runs `git reset --hard HEAD^` for /undo and similarly for /diff
- aider gives a shell to execute the command
- aider "syncs" with the last commits on startup, possibly repopulating its chat, and assumes ownership over the last commits on startup if done by aider.

Currently exiting and entering back into aider makes /undo and /diff less useful than it could be.

**Comment by paul-gauthier** [comment]
I added some more helpful error messages that suggest trying `/git diff` or `/git reset --hard HEAD^`. I wouldn't want aider to directly do git operations on non-aider commits through the `/undo` and `/diff` commands though. That could be very confusing and possibly lead to unexpected destructive changes to git history.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
