### ISSUE TITLE
Option to disallow adding link contents

### ISSUE THREAD

**Issue by david-strejc** [paul-gauthier/aider#762]
### Issue

I want to add commandline and config option for inital complete disabling and / or setting initial "add URL to context" to No.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you help me understand why? What are you trying to do?

**Comment by david-strejc** [comment]
> Thanks for trying aider and filing this issue.
> 
> Can you help me understand why? What are you trying to do?

When I copy paste some code and if it contains URL aider automatically converts this URL to "would you like to add URL to the context" - when I for example paste log from browser console it many times contains a lot of URLs and I am asked many times if I want to add them to the context.

**Comment by paul-gauthier** [comment]
I'm not sure it's appropriate to add an option for this special case. I think you can probably just say "no" when asked?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by masonc15** [comment]
@paul-gauthier This issue comes up for me all the time in a very frustrating way. I constantly paste in markdown snippets, documentation, or even HTML code including URL links and just sitting there typing "n" over and over again as aider asks me if I want to add that URL to the chat. I almost never do. It's a cool feature but could it _please_ be configurable or have some sort of toggle so aider is not always asking about adding URLs?

Thanks for the consideration, I really love aider and I want to continue using it as much as I can!
