### ISSUE TITLE
Are the large Torch and nvidia libraries necessary for common use?

### ISSUE THREAD

**Issue by codeninja** [paul-gauthier/aider#819]
### Issue

![image](https://github.com/paul-gauthier/aider/assets/14914/10c6450c-33cf-46b5-960a-cd7d465e7583)

So here's my issue... I run `venv` for virtual environments for each project and in every project I have I invariably load in Aider-chat. These packages are brought in are many gigs worth of libraries and executables and with 50 some odd installations of Aider I've noticed some file bloat.

My simple question is, is there a need for these libraries to be installed for common use or is this something that could be pruned from the requirements?

### Version and model info

aider-chat-0.43.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The install size went way up for aider v0.43.0. This is because aider uses vector search for the `/help` command, which requires pytorch. In some systems, the `torch` package brings in gigabytes of GPU dependencies.

I've just made some changes to dramatically reduce the size of the install. Aider will now install the CPU-only version of `torch`, which is much smaller.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. You may need to remove your existing virtual environment (to clean up the old install) and install in a fresh virtual env to actually reduce the disk usage.

Also, you can [install aider via pipx](https://aider.chat/docs/install/pipx.html) to install it once on your system and use it within any project you are working on. This will also make sure aider's dependencies don't conflict with your python project's dependencies.

**Comment by codeninja** [comment]
Outstanding.  I appreciate the rapid turnaround time. I will try this out
as soon as I can.

**Comment by lescientifik** [comment]
Was going to ask the same !! Thanks for the answer !

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by codeninja** [comment]
Yeah it's working well. Thanks for the update.
