### ISSUE TITLE
Issue with Aider installation

### ISSUE THREAD

**Issue by janbaz497** [paul-gauthier/aider#859]
Hello, 
I am new to AI coding. I followed a YouTube video to install Aider, Python, VS Code, and git. After that, I ran install aider in the terminal, which seemed to work. Then i add my api code from OpenAI. However, I keep getting the following error message whenever I try to ask Aider something:
![image](https://github.com/user-attachments/assets/914d49af-0ca5-4d61-9bf7-bc02d08bd4a3)
![image](https://github.com/user-attachments/assets/67e4cb58-cb28-4df9-ba5a-02aa8cc0c387)

Can someone help me please?

Thank you a lot!

Jan

**Comment by ceabarr** [comment]
Have you used "export" command to export your openai api key before running aider? Also if you are trying to run a local model, you have to download it and start the server first. For example "ollama serve" or "ollama run deepseek-coder-v2"

**Comment by janbaz497** [comment]
i used setx OPENAI_API_KEY (my key) i am working on windows. I enter the api key an the terminal said that it saved the new value

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Did you set any unusual parameters like the OpenAI API base? As in, are you accessing the normal openai api endpoint or something else?

**Comment by PhunkyBob** [comment]
Can you type in you terminal 
`echo %OPENAI_API_KEY%`

If it writes `%OPENAI_API_KEY%` you should restart your terminal or type `set OPENAI_API_KEY=<your key>`.

**Comment by paul-gauthier** [comment]
Also, you need to start a new shell after the setx, for it to take effect.

**Comment by janbaz497** [comment]
Hey,

thank you for the help.

Here is a screenshot: 
![image](https://github.com/user-attachments/assets/adb35cd0-9766-4cc9-9441-f989669f5825)
I think there is a problem with my api key. I generate 2 new keys but they dont work.

**Comment by PhunkyBob** [comment]
In "command" environment, you don't have to add spaces around the `=` sign: 
`set OPEN_API_KEY=bimbamboum`

Since you are using PowerShell, I guess you have to do:
`$env:OPEN_API_KEY = "bimbamboum"` (notice the `"` sign).

Best thing would be to set the variable for the long term with:
`setx OPEN_API_KEY bimbamboum`
then restart a new instance of your shell.

Verify with:
`echo $env:OPEN_API_KEY`

**Comment by janbaz497** [comment]
Thank you guys!

My mistake was that i tried to set my API-Keys with set command in bash. 
In bash you should use export and thank you PhunkyBob for the tip with the space around =.
Now i can programm and this tool is very cool. Thank you paul for this!

**Comment by kowalski-ptr** [comment]
Paul, I think we need to improve the installation and first-run instructions for Aider, especially for beginners who aren't using OpenAI api key. The instructions on the website are a bit of a jumble. Today, I spent two hours trying to get Aider to run, mainly because after installation and setting up the Anthropic API key, I tried to run Aider following the aider.docs instructions with the sipmly command: aider. This resulted in an error message about an incorrectly configured OpenAI API key environment variable. However, after setting up the Anthropic API key, we don't want to use OpenAI, which Aider tries to match by default. Only after a long struggle and searching through dozens of pages of documentation, issues, and instructions did I learn that I needed to use the command aider --sonnet to run the model I wanted directly without interference from the OpenAI API key. By the way, thank you very much and great respect for your work and contribution to Aider, which is truly something remarkable.

The aider.docs instructions should be as follows:
If you want to run Aider on another LLM and without any API key from OpenAI, you should do the following in the case of using Claude Sonnet:
1. 
# Install aider
python -m pip install aider-chat

2.
# Don't run aider yet, but first set up the Anthropic API key
setx ANTHROPIC_API_KEY <key> 

3.
# If you're on Windows, restart the shell after using setx

4.
# To run aider, you first have to go to the directory with your git repo files. If you are in your git repo, type: aider --sonnet

5.
# Now it should work. The same steps apply for other LLMs, but with the following changes: point 2. setx Name_LLM_API_KEY <key> and point 4. Run your specific LLM model by typing the model name you'll find in the Aider documentation: aider --modelName
