### ISSUE TITLE
Clash between Aider's default fence and markdown's fenced code blocks

### ISSUE THREAD

**Issue by bulzak** [paul-gauthier/aider#866]
### Issue

Both aider and markdown fences use ```, so aider struggles with generated markdown documentation that has code blocks. This could indicate that making the fence parametrizable could help walkaround this issue or similar clashes in the future.

My current workaround is to generate asciidoc. But there's a lot of markdown in the wild so we're often stuck with that as input in legacy repos.

PS: love the tool, thanks!

### Version and model info

Aider: v0.43.4
Model: DeepSeek-Coder-V2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider already picks fences based on the contents of the files being edited. What makes you think there is a problem?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by daninus14** [comment]
Hi, I just experienced this issue. the LLM generated a markdown file which contained a code block, and aider saved the commit of the file and excluded everything from the beginning of the code block until the end of the file, so that I basically lost a lot of the output which was generated in the commit (I still have it in the chat history). My workaround idea was to tell aider to generate code blocks always specifying a language, and if there is no language like when it generate directory structures, use `text` as the language.

**Comment by alexanderturner** [comment]
Also seeing this when getting Aider to write documentation. Running 0.86.1 on aarch64-darwin. Have seen it across different projects, Swift, go, and other Markdown repos. Asking it to produce Markdown seems to fail when it hits a URL then tries to create 10 new files with filenames like "{" or other parts of code blocks, etc.
