### ISSUE TITLE
Repo Map - Future Work

### ISSUE THREAD

**Issue by alok87** [paul-gauthier/aider#872]
### Issue

https://aider.chat/2023/10/22/repomap.html
<img width="788" alt="image" src="https://github.com/user-attachments/assets/3b8a231c-210e-4a47-a59b-87c9d9edef84">

### How can we help and contribute back! 

How can we help contributing this feature (part1) ? 
```
but it’s also an important foundation for future work on automatically finding all the code which will need to be changed (1).
```

So that we do not need to add and tell which files to change!

// @hariharpatel1

_No response_

**Comment by nevercast** [comment]
This is something I really want to have the time to attempt. Though I don't see that soon.

It's essentially a Graph RAG problem, the repomap is good to go, you just need a means of scoring files so that those that are more relevant are selected.

**Comment by xAlstrat** [comment]
I'm also interested in that materia. Repo-map is great, but I think we can have 2 mayor improvements.
1. Detailed repo map: maybe including comments or a description for each file, metadata, etc.
2. Finding EXACTLY (maybe more files but never less) what files are needed to generate a solution and the edit them. I think a good solution here is RAG with a Vector store, but it seems to be a little slow compared to how fast aider is. Maybe this doesn't matter much because genAI models will be faster in the future. I also read in docs something about graph ranking algorithms.

Do know any other ways to solve this? I'm going to look at that Graph Rag algorithm!

Maybe in the discord we can find more details about how to contribute.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
