### ISSUE TITLE
getting stuck on mac osx and on WSL

### ISSUE THREAD

**Issue by 0x33dm** [paul-gauthier/aider#913]
### Issue

Basically after i add a file to aider it asks if i would like to add it, i say "yes" and it just hangs.

i'm inside a git repo from a project i'm already working on.

I seen in another thread the recommendation to try "--no-git" but when i do then the "add" command doesn't bring an autocomplete.

the repository isn't too large if you only consider the source files ( ignore everything from all .gitignore files ), but if you consider all of those files then i guess it's really big as there are loads of dependencies.

is there a way of getting it unstuck? as you can see not even ctrl+c is quitting it.

When using on a new folder empty folder without having a git repo it's working as expected.

Mac OSX:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/5ab4addc-55d3-4319-8388-806841bad12c">

WSL:
![image](https://github.com/user-attachments/assets/7061d8fb-a046-4727-b6d9-a0d345df1e8b)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like you meant to do `/add` with a leading slash.

What you've typed has sent the request to the LLM. Aider is awaiting the response. Sometimes the very first message you send can also take awhile because aider needs to index your repo. Be patient. It will cache the index and work quickly on subsequent requests.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
