### ISSUE TITLE
feature request: /rageedit to edit last diff in rage

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#96]
Sometimes gpt stubbornly will not understand what you say and do too much.

In this case, a "rage edit" command is appropriate to invoke to edit the diff in rage.

**Comment by alexanderkjeldaas** [comment]
this command could also invoke `git add -i` for interactive add of the commit.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

I'm not exactly sure I understand your request. But I just added a FAQ entry that you might find helpful:
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files

**Comment by alexanderkjeldaas** [comment]
It's not that example I'm thinking of.  I haven't seen gpt not being able to edit files (but I'm using 3.5 which seems to not have that problem).  I'm thinking of when the diff contains unneeded changes that I want to remove. I have 3 choices:

1. /undo + update the command and retry
2. edit externally + `git commit -a --amend`
3. /rageedit which would do #2 from within aider, but instead use the equivalent of:
```
git reset HEAD^
git add -i
```

**Comment by paul-gauthier** [comment]
Ah I see. In my experience coding with GPT, in this situation I would simply make an edit in my editor to fix/improve the code, commit that and move on (kind of like your option 2). That fixes the **code**, but doesn't worry about the fact that there's a commit in the history which wasn't perfect.

I'm not sure it's in scope for aider to strive for a perfect commit history. Coding with GPT is very much a collaborative and iterative process. Aider relies on git for safety so that you can always undo something that GPT does.

 If you want to tidy up the commit history, you probably need to use git on the command line to rebase or `--amend`, etc.

Here's some info on how aider uses git that might be relevant:
https://aider.chat/docs/faq.html#how-does-aider-use-git

**Comment by paul-gauthier** [comment]
I just [asked aider to add an in-chat /git command](https://github.com/paul-gauthier/aider/commit/c05efad2742abc59bf2d81a183cadc6ab327a3df) so you can run git commands without having to leave the chat. It's not the automagic functionality you were describing, but it might simplify the workflow you're looking for.

**Comment by joshuavial** [comment]
My practice is to do a rebase periodically to keep the git history in order. I'm still on the fence personally about how I feel about the large diffs that gpt-4 puts in the git history.

I like the idea of keeping as few opinions as possible in aider itself and letting folks do things the way they want.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
